### ISSUE TITLE
Tests disabled because PhantomJS has been crashing on CI.

### ISSUE THREAD

**Issue by neoeno** [moneyadviceservice/frontend#886]
Flagging this so we don't forget to keep an eye on it.

See: https://github.com/moneyadviceservice/frontend/commit/685b87ca09e7d395349317ef002b7a58a9dc65bb & https://github.com/moneyadviceservice/frontend/commit/928a13bd4660c35dbea6f023d5f9f5beca8ca7d1

We disabled these because PhantomJS kept crashing when it hit them, which caused the build to fail. This only happens on some machines.

**Comment by neoeno** [comment]
PhantomJS 2 was released the other day. Poltergeist doesn't officially support it yet, but I tried master and it still fails ;(

**Comment by neoeno** [comment]
Have started seeing this error intermittently (with both successes and silent crashes, so we've now got 3 intermittent outputs...)

```
  @javascript
  Scenario: Sign up with an existing email address                    # features/newsletter_signup.feature:23
    When I have already signed up for the newsletter                  # features/step_definitions/newsletter_signup_steps.rb:15
      One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

      Error: Script error for: ujs
      http://requirejs.org/docs/errors.html#scripterror
      Error: Script error for: ujs
      http://requirejs.org/docs/errors.html#scripterror
          at http://127.0.0.1:54890/assets/requirejs/require.js:142 in defaultOnError
          at http://127.0.0.1:54890/assets/requirejs/require.js:546 in onError
          at http://127.0.0.1:54890/assets/requirejs/require.js:1690
      Error: Script error for: componentLoader
      http://requirejs.org/docs/errors.html#scripterror
      Error: Script error for: componentLoader
      http://requirejs.org/docs/errors.html#scripterror
          at http://127.0.0.1:54890/assets/requirejs/require.js:142 in defaultOnError
          at http://127.0.0.1:54890/assets/requirejs/require.js:546 in onError
          at http://127.0.0.1:54890/assets/requirejs/require.js:1690
      Error: Script error for: eventsWithPromises
      http://requirejs.org/docs/errors.html#scripterror
      Error: Script error for: eventsWithPromises
      http://requirejs.org/docs/errors.html#scripterror
          at http://127.0.0.1:54890/assets/requirejs/require.js:142 in defaultOnError
          at http://127.0.0.1:54890/assets/requirejs/require.js:546 in onError
          at http://127.0.0.1:54890/assets/requirejs/require.js:1690 (Capybara::Poltergeist::JavascriptError)
      ./features/step_definitions/newsletter_signup_steps.rb:7:in `/^I sign up to the newsletter with a valid email address$/'
      ./features/step_definitions/newsletter_signup_steps.rb:17:in `/^I have already signed up for the newsletter$/'
      ./features/support/env.rb:54:in `call'
      ./features/support/env.rb:54:in `block in <top (required)>'
      ./features/support/cucumber_extensions.rb:37:in `visit_feature_element_twice'
      ./features/support/cucumber_extensions.rb:12:in `block in accept'
      ./features/support/cucumber_extensions.rb:10:in `each'
      ./features/support/cucumber_extensions.rb:10:in `accept'
      features/newsletter_signup.feature:24:in `When I have already signed up for the newsletter'
    And I sign up to the newsletter again with the same email address # features/step_definitions/newsletter_signup_steps.rb:20
    Then I should see a message that my subscription was successful   # features/step_definitions/newsletter_signup_steps.rb:25
```

Probably unrelated, but might be a clue.
